version: "2"

run:
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  exclusions:
    presets: []
  enable:
    - bodyclose
    - gosec
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace

formatters:
  enable:
    - goimports
