includes:
  - from_url:
      url: charmbracelet/meta/main/goreleaser-full.yaml

variables:
  main: "./cmd/seedify"
  description: "Create seed phrases deterministically from SSH keys"
  github_url: "https://github.com/complex-gh/seedify"
  maintainer: "Carlos A Becker <carlos@charm.sh>"
  brew_commit_author_name: "Carlos A Becker"
  brew_commit_author_email: "carlos@charm.sh"


