# GoReleaser configuration for seedify
# See https://goreleaser.com for documentation

version: 2

project_name: seedify

builds:
  - id: seedify
    main: ./cmd/seedify
    binary: seedify
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    # Only include the binary (no extra files)
    files:
      - none*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

snapshot:
  version_template: '{{ .Tag }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: complex-gh
    name: seedify
  mode: replace
  header: |
    ## {{ .ProjectName }} {{ .Tag }}
    
    {{ .ReleaseNotes }}
  footer: |
    ---
    
    **Full Changelog**: https://github.com/complex-gh/seedify/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew Casks (replaces deprecated 'brews')
homebrew_casks:
  - name: seedify
    binaries:
      - seedify
    homepage: https://github.com/complex-gh/seedify
    description: Create seed phrases deterministically from SSH keys
    caveats: |
      seedify is not signed/notarized. On first run, macOS may block it.
      If you see "seedify is damaged and cannot be opened", run:
        xattr -dr com.apple.quarantine $(which seedify)
    # Remove quarantine attribute on install since binary is not signed
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seedify"]
          end
    commit_msg_template: |
      {{ .ProjectName }} {{ .Tag }}

      Created with https://github.com/goreleaser/goreleaser
    repository:
      owner: complex-gh
      name: homebrew-seedify
      token: '{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}'

nfpms:
  - id: seedify
    package_name: seedify
    file_name_template: '{{ .ConventionalFileName }}'
    maintainer: complex@ft.hn
    description: Create seed phrases deterministically from SSH keys
    homepage: https://github.com/complex-gh/seedify
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin

# Docker v2 (replaces deprecated 'dockers')
dockers_v2:
  - id: seedify
    ids:
      - seedify
    dockerfile: Dockerfile
    images:
      - ghcr.io/complex-gh/seedify
    tags:
      - '{{ .Tag }}'
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
